/*
 * GianTigle Supermarkets
 * This is a simple supermarket example interface for CS6650 at Northeastern University 
 *
 * OpenAPI spec version: 1.11
 * Contact: i.gorton@northeastern.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.TopStoresStores;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * TopStores
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-04T08:27:47.105Z[GMT]")
public class TopStores {
  @SerializedName("stores")
  private List<TopStoresStores> stores = null;

  public TopStores stores(List<TopStoresStores> stores) {
    this.stores = stores;
    return this;
  }

  public TopStores addStoresItem(TopStoresStores storesItem) {
    if (this.stores == null) {
      this.stores = new ArrayList<TopStoresStores>();
    }
    this.stores.add(storesItem);
    return this;
  }

   /**
   * Get stores
   * @return stores
  **/
  @Schema(description = "")
  public List<TopStoresStores> getStores() {
    return stores;
  }

  public void setStores(List<TopStoresStores> stores) {
    this.stores = stores;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TopStores topStores = (TopStores) o;
    return Objects.equals(this.stores, topStores.stores);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stores);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TopStores {\n");
    
    sb.append("    stores: ").append(toIndentedString(stores)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
