/*
 * GianTigle Supermarkets
 * This is a simple supermarket example interface for CS6650 at Northeastern University 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: i.gorton@northeastern.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Purchase;
import io.swagger.client.model.ResponseMsg;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PurchaseApi
 */
@Ignore
public class PurchaseApiTest {

    private final PurchaseApi api = new PurchaseApi();

    /**
     * A customer purchase from a store
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void newPurchaseTest() throws ApiException {
        Purchase body = null;
        Integer storeID = null;
        Integer custID = null;
        String date = null;
        api.newPurchase(body, storeID, custID, date);

        // TODO: test validations
    }
}
